[package]
name = "actix-app"
version = "0.1.0"
edition = "2021"
rust-version = "1.78.0"

[dependencies]
actix-web = "4.9.0"
serde = { version = "1.0.216", features = ["derive"] }
chrono = { version = "0.4.39", features = ["serde"] }
thiserror="2.0.8"
env_logger = "0.11.6"

